const config = {
    debug: true,
    updateRate: 30, // updates per second
    unitScale: 1.5,
    icons: {        // automaton font
        storage: 'a',
        star: 'b',
        neutral: 'i',
        hungry: 'x',
        full: 'd',
        happy1: 'k',
        happy2: 'g',
        happy3: 'h',
        happy4: 'z',
        sad1: 'c',
        sad2: 'l',
        sad3: 'e',
        sad4: 'm',
        extractor: 'f',
        train: 'j',
        load: 'o',
        save: 'n',
        new: 'p',
        delete: 'q',
        select: 'r',
        play: 's',
        pause: 't',
        download: 'v',
        upload: 'u',
        scope: 'w',
        city: 'y',
        power1: '1',
        power2: '2',
        worker: '3'
    },
    times: {    // measured in seconds
        resourceGrowTime: 1,
        resourceExtraction: 1,
        productManufacturing: 2,
        productRefinement: 3,
        consumerFeedRate: 3,
        consumerFeedRateUnpowered: 12,
        powerStationFuelConsumption: 4,
        itemThroughPipe: 0.2,
        itemThroughStorage: 0.2,
        slowTrain: 2,
        fastTrain: 0.5,
        switchRotateTime: 1
    }
};
