const config = {
    debug: true,
    tickRate: 30,
    unitScale: 1.5,
    icons: {
        storage: 'a',
        star: 'b',
        neutral: 'i',
        hungry: 'x',
        full: 'd',
        happy1: 'k',
        happy2: 'g',
        happy3: 'h',
        happy4: 'z',
        sad1: 'c',
        sad2: 'l',
        sad3: 'e',
        sad4: 'm',
        miner: 'f',
        train: 'j',
        load: 'o',
        save: 'n',
        new: 'p',
        delete: 'q',
        select: 'r',
        play: 's',
        pause: 't',
        download: 'v',
        upload: 'u',
        scope: 'w',
        city: 'y',
        power1: '1',
        power2: '2',
        worker: '3'
    }
};
